services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=acuchat_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234

  llm-service:
    image: ollama/ollama:latest
    container_name: acu-llm
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11435:11434"

  webapp:
    build: ./webapp
    volumes:
      - ./webapp:/app
      - hf_cache:/root/.cache/huggingface
      - ./manual_data:/app/manual_data
      - chroma_data:/app/db/chroma
    ports:
      - "8000:8000"
    env_file:
      - ./webapp/.env
    depends_on:
      - db
      - llm-service

volumes:
  postgres_data:
  ollama_data:
  hf_cache:
  chroma_data:
