# Generated by Django 5.0.14 on 2026-04-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255, verbose_name='Kaynak Adı (PDF veya Link Adı)')),
                ('raw_text', models.TextField(verbose_name='Temizlenmiş Metin')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
