# Generated by Django 5.0.14 on 2026-05-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_syncstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
    ]
